// <auto-generated />
namespace Example.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SectionChilds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SectionChilds));
        
        string IMigrationMetadata.Id
        {
            get { return "201512140405166_SectionChilds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
